import pathlib
import argparse
import re

def remove_files (target_path: str):
    # Go thru all .inc Files
    for inc_file in target_path.rglob ("*.inc"):
        try:
            # Delete .inc File
            inc_file.unlink ()

            # Show Deleted File
            print (f"Deleted: {inc_file.name}")
        except:
            print (f"Failed to Delete \"{inc_file}\"!")

def clean_inf_files (target_path: str):
    # Set Replacements
    target_replacements = {
        r"INF_VERSION\s*=": "INF_VERSION                    =",
        r"BASE_NAME\s*=": "BASE_NAME                      =",
        r"FILE_GUID\s*=": "FILE_GUID                      =",
        r"MODULE_TYPE\s*=": "MODULE_TYPE                    =",
        r"VERSION_STRING\s*=": "VERSION_STRING                 =",
        r"ENTRY_POINT\s*=": "ENTRY_POINT                    =",
        r"   RAW\|": "  RAW|",
        r"   TE\|": "  TE|",
        r"   DXE_DEPEX\|": "  DXE_DEPEX|",
        r"   PE32\|": "  PE32|",
    }

    # Go thru all .inf Files
    for file in target_path.rglob ("*.inf"):
        try:
            # Get File Contents
            content = file.read_text (encoding="utf-8")
        except:
            # Report Read Error
            print (f"Failed to Read File Contents of \"{file}\"!")
            continue

        # Verify Clean State
        if "AUTOGENERATED" not in content:
            print (f"Skipped: {file.name}")
            continue

        # Get File Lines
        lines = content.splitlines ()

        # Remove first 6 Lines
        lines = lines[6:]

        # Combine File Lines
        content = "\n".join (lines)

        # Replace Target Lines
        for pattern, replacement in target_replacements.items ():
            content = re.sub (pattern, replacement, content)

        # Replace "DXE_DRIVER" with "UEFI_DRIVER"
        if "Depex" not in content:
            content = content.replace ("DXE_DRIVER", "UEFI_DRIVER")

        # Remove Footer
        content = content.split("# AUTOGEN ENDS")[0]

        # Add Empty Line
        content = content.strip () + "\n"

        # Write Changes
        file.write_text (content, encoding="utf-8")

        # Show Progress
        print (f"Cleaned: {file.name}")

def main ():
    # Set Arguments
    parser = argparse.ArgumentParser (description="Clean the Output Files of UEFIReader.")
    parser.add_argument ("-d", "--device", type=str, help="The Codename of the Device.")

    # Parse Arguments
    args = parser.parse_args ()

    # Get Base Path
    target_path = pathlib.Path.cwd ()

    # Append Device Codename
    if args.device != None:
        target_path = target_path / args.device

    # Remove Unnecessary Files
    remove_files (target_path)

    # Clean .inf Files
    clean_inf_files (target_path)

# Verify Run Enviroment
if __name__ == "__main__":
    main ()
